#logging.level.com.zj=trace
#\u5F53\u524D\u9879\u76EE\u4E0B\u751F\u6210log\u65E5\u5FD7
#logging.file=springboot.log

#logging.path=/spring/log
logging:
  #path: /spring/log
  #file: springboot.log

spring:
  profiles:
    active: dev
   
---
server:
  port: 8084
spring:
  profiles: dev
  
  
---
server:
  port: 8085
spring:
  profiles: prod
